In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import keras
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras.models as km
from keras.models import Sequential
from keras import activations, initializers, regularizers, constraints
from keras.layers import Dense, Activation

In [4]:
df = sns.load_dataset("penguins")
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [5]:
df.shape

(344, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [7]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [8]:
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [11]:

df['sex'].value_counts()

sex
Male      168
Female    165
Name: count, dtype: int64

In [12]:

df['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [13]:

df['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [15]:

df['bill_length_mm'].value_counts()

bill_length_mm
41.1    7
45.2    6
39.6    5
50.5    5
50.0    5
       ..
35.6    1
36.8    1
43.1    1
38.5    1
49.9    1
Name: count, Length: 164, dtype: int64

In [16]:
df['bill_depth_mm'].value_counts()

bill_depth_mm
17.0    12
18.6    10
17.9    10
15.0    10
18.5    10
        ..
13.2     1
14.9     1
21.5     1
20.2     1
17.4     1
Name: count, Length: 80, dtype: int64

In [17]:
df["sex"].fillna("male",inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_18180\232772562.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["sex"].fillna("male",inplace=True)

In [18]:
df['bill_length_mm'] = df['bill_length_mm'].fillna(41.1)

In [19]:
df['bill_depth_mm'] = df['bill_depth_mm'].fillna(17.0)

In [20]:
df['island'] = df['island'].fillna('Biscoe')

In [21]:
df['species'] = df['species'].fillna('Adelie')

In [22]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    2
body_mass_g          2
sex                  0
dtype: int64

In [23]:

df['flipper_length_mm'] = df['flipper_length_mm'].fillna(df['flipper_length_mm'].mode()[0])
df['body_mass_g'] = df['body_mass_g'].fillna(df['body_mass_g'].mode()[0])

In [24]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [37]:
# 1. Create a copy and label encode the categories directly using pandas
df_encoded = df.copy()
df_encoded['species'] = df_encoded['species'].astype('category').cat.codes
df_encoded['island'] = df_encoded['island'].astype('category').cat.codes
df_encoded['sex'] = df_encoded['sex'].astype('category').cat.codes

# 2. Define your X and y from the encoded dataframe
y = df_encoded['body_mass_g']
X = df_encoded.drop(columns=['body_mass_g'])

# 3. Do the Train-Test Split using the new numeric X
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=123)

# 4. Scale the features (This will now run perfectly!)
sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)

In [38]:
train_X.shape

(240, 6)

In [46]:
model = Sequential()
model.add(Dense(units = 12, kernel_initializer = 'uniform', activation = 'relu', input_dim = 6))
model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'linear'))

C:\Users\Asus\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [40]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │            77 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 4)              │            28 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 182 (728.00 B)

 Trainable params: 182 (728.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.compile(loss='mean_squared_error', optimizer='adam',metrics=["mae"])

In [42]:
print(train_X.shape)
print(train_y.shape)

(240, 6)
(240,)

In [48]:
model.fit(train_X, train_y, epochs=150, batch_size=10, validation_split=0.1)

# Evaluate the model
mse = model.evaluate(test_X, test_y)
print(f'Test Mean Squared Error: {mse}')

Epoch 1/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 18440200.0000 - mae: 4217.2339 - val_loss: 18642630.0000 - val_mae: 4223.9341
Epoch 2/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18439966.0000 - mae: 4217.2070 - val_loss: 18642362.0000 - val_mae: 4223.9023
Epoch 3/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18439630.0000 - mae: 4217.1685 - val_loss: 18641926.0000 - val_mae: 4223.8530
Epoch 4/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18439024.0000 - mae: 4217.0991 - val_loss: 18641046.0000 - val_mae: 4223.7563
Epoch 5/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18437764.0000 - mae: 4216.9614 - val_loss: 18639230.0000 - val_mae: 4223.5610
Epoch 6/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18435196.0000 - mae: 4216.6831 - val_loss: 18635640.0000 - val_mae: 4223.1792
Epoch 7/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18430474.0000 - mae: 4216.1738 - val_loss: 18629146.0000 - val_mae: 4222.4946
Epoch 8/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18422114.0000 - mae: 4215.2803 - val_loss: 18618398.0000 - val_mae: 4221.3623
Epoch 9/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18408770.0000 - mae: 4213.8496 - val_loss: 18601604.0000 - val_mae: 4219.5986
Epoch 10/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18389192.0000 - mae: 4211.7383 - val_loss: 18576360.0000 - val_mae: 4216.9546
Epoch 11/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18359998.0000 - mae: 4208.6201 - val_loss: 18541562.0000 - val_mae: 4213.2974
Epoch 12/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18319438.0000 - mae: 4204.2515 - val_loss: 18493026.0000 - val_mae: 4208.2007
Epoch 13/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18264414.0000 - mae: 4198.3794 - val_loss: 18427494.0000 - val_mae: 4201.3062
Epoch 14/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18191350.0000 - mae: 4190.4888 - val_loss: 18341946.0000 - val_mae: 4192.3013
Epoch 15/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18098734.0000 - mae: 4180.5376 - val_loss: 18233614.0000 - val_mae: 4180.8813
Epoch 16/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17982934.0000 - mae: 4167.9248 - val_loss: 18099536.0000 - val_mae: 4166.6733
Epoch 17/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17838172.0000 - mae: 4152.2759 - val_loss: 17936862.0000 - val_mae: 4149.3184
Epoch 18/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17662580.0000 - mae: 4133.1211 - val_loss: 17740798.0000 - val_mae: 4128.2891
Epoch 19/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17452494.0000 - mae: 4110.1206 - val_loss: 17510102.0000 - val_mae: 4103.3682
Epoch 20/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17210440.0000 - mae: 4083.1670 - val_loss: 17229492.0000 - val_mae: 4072.8440
Epoch 21/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16918394.0000 - mae: 4050.5469 - val_loss: 16919614.0000 - val_mae: 4038.6438
Epoch 22/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16592645.0000 - mae: 4013.7021 - val_loss: 16554300.0000 - val_mae: 3997.8762
Epoch 23/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16212009.0000 - mae: 3970.1514 - val_loss: 16158545.0000 - val_mae: 3952.9368
Epoch 24/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15800894.0000 - mae: 3922.0784 - val_loss: 15697935.0000 - val_mae: 3899.9160
Epoch 25/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15326711.0000 - mae: 3865.9417 - val_loss: 15204864.0000 - val_mae: 3841.7224
Epoch 26/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14817890.0000 - mae: 3804.0095 - val_loss: 14645296.0000 - val_mae: 3774.3152
Epoch 27/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14244344.0000 - mae: 3733.3953 - val_loss: 14064567.0000 - val_mae: 3702.2766
Epoch 28/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13649739.0000 - mae: 3657.3875 - val_loss: 13421391.0000 - val_mae: 3620.2314
Epoch 29/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12986746.0000 - mae: 3570.7942 - val_loss: 12772076.0000 - val_mae: 3534.2607
Epoch 30/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12324766.0000 - mae: 3480.6143 - val_loss: 12056029.0000 - val_mae: 3435.9451
Epoch 31/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11617127.0000 - mae: 3379.8721 - val_loss: 11328243.0000 - val_mae: 3331.3408
Epoch 32/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10889925.0000 - mae: 3272.1714 - val_loss: 10598396.0000 - val_mae: 3221.1650
Epoch 33/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10164053.0000 - mae: 3159.4172 - val_loss: 9860569.0000 - val_mae: 3103.5381
Epoch 34/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9436981.0000 - mae: 3040.4983 - val_loss: 9133124.0000 - val_mae: 2980.2639
Epoch 35/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8713364.0000 - mae: 2914.5671 - val_loss: 8439020.0000 - val_mae: 2854.8625
Epoch 36/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8022868.0000 - mae: 2786.5266 - val_loss: 7752632.5000 - val_mae: 2721.2761
Epoch 37/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7352701.0000 - mae: 2652.2559 - val_loss: 7106518.0000 - val_mae: 2585.2200
Epoch 38/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6717511.5000 - mae: 2517.2366 - val_loss: 6509069.5000 - val_mae: 2448.1255
Epoch 39/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6133435.5000 - mae: 2381.6016 - val_loss: 5957759.5000 - val_mae: 2309.5952
Epoch 40/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5595599.5000 - mae: 2245.6282 - val_loss: 5460606.0000 - val_mae: 2171.8110
Epoch 41/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5107085.5000 - mae: 2113.8396 - val_loss: 5028059.5000 - val_mae: 2039.4906
Epoch 42/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4672664.0000 - mae: 1985.1990 - val_loss: 4643817.5000 - val_mae: 1910.6986
Epoch 43/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4292183.5000 - mae: 1867.7281 - val_loss: 4305007.5000 - val_mae: 1803.4935
Epoch 44/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3955384.0000 - mae: 1761.3959 - val_loss: 4009621.2500 - val_mae: 1713.6056
Epoch 45/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3660890.2500 - mae: 1668.2040 - val_loss: 3758140.7500 - val_mae: 1648.1509
Epoch 46/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3398675.2500 - mae: 1584.8704 - val_loss: 3542771.2500 - val_mae: 1592.2623
Epoch 47/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3172195.5000 - mae: 1514.2118 - val_loss: 3343476.0000 - val_mae: 1541.2344
Epoch 48/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2964715.7500 - mae: 1454.6875 - val_loss: 3170762.0000 - val_mae: 1500.3246
Epoch 49/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2781982.0000 - mae: 1404.6865 - val_loss: 3011245.2500 - val_mae: 1468.5194
Epoch 50/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2611183.7500 - mae: 1360.7085 - val_loss: 2868146.2500 - val_mae: 1436.5112
Epoch 51/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2456155.7500 - mae: 1317.4756 - val_loss: 2734387.7500 - val_mae: 1401.5986
Epoch 52/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2314731.2500 - mae: 1277.4749 - val_loss: 2604538.0000 - val_mae: 1364.4355
Epoch 53/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2176224.5000 - mae: 1234.2080 - val_loss: 2483191.0000 - val_mae: 1325.7061
Epoch 54/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2050221.8750 - mae: 1194.2115 - val_loss: 2370206.2500 - val_mae: 1286.9720
Epoch 55/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1928867.1250 - mae: 1153.9628 - val_loss: 2262686.2500 - val_mae: 1250.5258
Epoch 56/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1818173.0000 - mae: 1115.3004 - val_loss: 2157640.2500 - val_mae: 1216.8759
Epoch 57/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1710264.7500 - mae: 1075.2130 - val_loss: 2060310.1250 - val_mae: 1182.7017
Epoch 58/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1612782.8750 - mae: 1039.0802 - val_loss: 1971727.5000 - val_mae: 1150.0850
Epoch 59/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1518929.7500 - mae: 1003.2805 - val_loss: 1887454.3750 - val_mae: 1116.4126
Epoch 60/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1432202.6250 - mae: 970.4611 - val_loss: 1808306.1250 - val_mae: 1086.6915
Epoch 61/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1353630.3750 - mae: 940.0112 - val_loss: 1730684.3750 - val_mae: 1061.2689
Epoch 62/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1278659.0000 - mae: 911.7191 - val_loss: 1664280.5000 - val_mae: 1040.1007
Epoch 63/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1208993.8750 - mae: 888.2238 - val_loss: 1605093.3750 - val_mae: 1019.8671
Epoch 64/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1150064.8750 - mae: 867.4261 - val_loss: 1544267.8750 - val_mae: 1002.4111
Epoch 65/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1089132.8750 - mae: 844.8184 - val_loss: 1492204.1250 - val_mae: 986.2148
Epoch 66/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1037201.4375 - mae: 825.5040 - val_loss: 1447229.6250 - val_mae: 974.3940
Epoch 67/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 990004.0625 - mae: 806.6262 - val_loss: 1406082.3750 - val_mae: 965.4235
Epoch 68/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 947977.2500 - mae: 789.5379 - val_loss: 1363668.7500 - val_mae: 954.3620
Epoch 69/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 908584.1250 - mae: 773.1129 - val_loss: 1327812.6250 - val_mae: 944.0989
Epoch 70/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 873561.1875 - mae: 757.0361 - val_loss: 1295486.6250 - val_mae: 934.4555
Epoch 71/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 842364.8125 - mae: 743.4700 - val_loss: 1265092.8750 - val_mae: 924.1999
Epoch 72/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 814295.1875 - mae: 730.5806 - val_loss: 1234707.1250 - val_mae: 912.9333
Epoch 73/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 787850.7500 - mae: 719.7852 - val_loss: 1214875.6250 - val_mae: 906.5020
Epoch 74/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 764985.8750 - mae: 711.2170 - val_loss: 1192802.1250 - val_mae: 897.8679
Epoch 75/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 742656.3750 - mae: 700.6454 - val_loss: 1173115.6250 - val_mae: 889.6857
Epoch 76/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 725030.1250 - mae: 692.6118 - val_loss: 1147500.1250 - val_mae: 877.9567
Epoch 77/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 707520.3125 - mae: 684.0997 - val_loss: 1132941.6250 - val_mae: 871.3440
Epoch 78/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 690984.6875 - mae: 676.2352 - val_loss: 1116877.5000 - val_mae: 863.7513
Epoch 79/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 677134.0625 - mae: 669.3407 - val_loss: 1100599.5000 - val_mae: 856.2102
Epoch 80/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 664407.2500 - mae: 663.0435 - val_loss: 1081515.1250 - val_mae: 848.1027
Epoch 81/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 651952.6875 - mae: 656.2419 - val_loss: 1070063.8750 - val_mae: 843.6197
Epoch 82/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 640495.6250 - mae: 650.7292 - val_loss: 1055199.2500 - val_mae: 836.9373
Epoch 83/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 630284.3125 - mae: 645.8873 - val_loss: 1041078.5625 - val_mae: 831.6643
Epoch 84/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 620338.0000 - mae: 641.6972 - val_loss: 1029350.6875 - val_mae: 828.5471
Epoch 85/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 611029.6875 - mae: 636.6816 - val_loss: 1013708.5625 - val_mae: 823.7480
Epoch 86/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 602095.8750 - mae: 632.4266 - val_loss: 1003049.3125 - val_mae: 820.5959
Epoch 87/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 594719.5625 - mae: 629.0250 - val_loss: 990008.0625 - val_mae: 816.8543
Epoch 88/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 586172.5000 - mae: 624.0709 - val_loss: 980677.8125 - val_mae: 814.2023
Epoch 89/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 578873.8750 - mae: 620.4753 - val_loss: 971956.9375 - val_mae: 811.7682
Epoch 90/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 571639.6875 - mae: 617.1780 - val_loss: 955905.5000 - val_mae: 805.3107
Epoch 91/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 564578.0000 - mae: 612.7280 - val_loss: 943324.8125 - val_mae: 800.5003
Epoch 92/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 558157.2500 - mae: 609.2782 - val_loss: 932101.9375 - val_mae: 796.2397
Epoch 93/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 551706.6875 - mae: 605.7403 - val_loss: 925708.2500 - val_mae: 793.9805
Epoch 94/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 545889.3750 - mae: 602.5466 - val_loss: 914543.7500 - val_mae: 789.6398
Epoch 95/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 539921.1250 - mae: 598.9977 - val_loss: 902169.0625 - val_mae: 783.8425
Epoch 96/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 534849.3125 - mae: 595.5492 - val_loss: 894768.9375 - val_mae: 781.7769
Epoch 97/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 528460.7500 - mae: 592.1341 - val_loss: 883104.5000 - val_mae: 775.7551
Epoch 98/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 523317.0625 - mae: 589.0051 - val_loss: 874708.8125 - val_mae: 771.7111
Epoch 99/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 518043.0000 - mae: 586.2844 - val_loss: 869208.0625 - val_mae: 770.4338
Epoch 100/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 512933.5938 - mae: 582.8993 - val_loss: 856428.5000 - val_mae: 763.8500
Epoch 101/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 507973.1562 - mae: 579.6981 - val_loss: 844441.6875 - val_mae: 758.4832
Epoch 102/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 502713.7500 - mae: 576.3608 - val_loss: 835580.9375 - val_mae: 754.5292
Epoch 103/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 498052.3750 - mae: 573.5975 - val_loss: 827581.6875 - val_mae: 750.2651
Epoch 104/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 493487.8125 - mae: 570.7720 - val_loss: 819800.0625 - val_mae: 746.7809
Epoch 105/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 489160.1250 - mae: 568.1859 - val_loss: 812153.5000 - val_mae: 742.7393
Epoch 106/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 484388.2500 - mae: 565.4001 - val_loss: 805068.5000 - val_mae: 739.5388
Epoch 107/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 480450.2812 - mae: 563.0185 - val_loss: 799264.7500 - val_mae: 736.5095
Epoch 108/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 475978.8750 - mae: 560.1998 - val_loss: 787499.0000 - val_mae: 730.0132
Epoch 109/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 472036.0312 - mae: 558.0847 - val_loss: 775649.5625 - val_mae: 723.3916
Epoch 110/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 468464.2188 - mae: 555.7800 - val_loss: 771842.2500 - val_mae: 721.9580
Epoch 111/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 463918.8438 - mae: 553.1508 - val_loss: 761741.4375 - val_mae: 716.0148
Epoch 112/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 459878.3750 - mae: 550.7054 - val_loss: 755450.9375 - val_mae: 712.5358
Epoch 113/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 455928.2812 - mae: 548.2854 - val_loss: 749409.6875 - val_mae: 709.4308
Epoch 114/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 452485.6562 - mae: 546.4299 - val_loss: 741648.3125 - val_mae: 704.5142
Epoch 115/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 448451.0625 - mae: 544.0089 - val_loss: 733522.0625 - val_mae: 700.0046
Epoch 116/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 445122.1875 - mae: 541.8491 - val_loss: 724234.6875 - val_mae: 694.3220
Epoch 117/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 441332.2812 - mae: 539.8625 - val_loss: 719765.1875 - val_mae: 692.3877
Epoch 118/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 437574.6562 - mae: 537.5760 - val_loss: 710839.1875 - val_mae: 686.8985
Epoch 119/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 434126.4688 - mae: 535.4441 - val_loss: 705252.5000 - val_mae: 683.7997
Epoch 120/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 430815.4688 - mae: 533.4052 - val_loss: 696937.4375 - val_mae: 679.3074
Epoch 121/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 427453.8438 - mae: 531.2921 - val_loss: 693224.0000 - val_mae: 676.6995
Epoch 122/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 424995.2188 - mae: 529.2899 - val_loss: 683236.6875 - val_mae: 670.8853
Epoch 123/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 420900.6562 - mae: 526.7810 - val_loss: 680422.1875 - val_mae: 668.9776
Epoch 124/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 417200.5938 - mae: 524.4753 - val_loss: 674903.3125 - val_mae: 665.9141
Epoch 125/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 414287.4375 - mae: 522.7130 - val_loss: 667780.7500 - val_mae: 661.7200
Epoch 126/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 410795.4688 - mae: 520.4886 - val_loss: 660978.6875 - val_mae: 657.8361
Epoch 127/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 407363.1562 - mae: 518.5429 - val_loss: 652073.5625 - val_mae: 653.2683
Epoch 128/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 404952.0000 - mae: 517.0671 - val_loss: 646967.6875 - val_mae: 649.9127
Epoch 129/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 401353.7812 - mae: 514.4790 - val_loss: 636852.4375 - val_mae: 644.5223
Epoch 130/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 397555.0312 - mae: 512.6319 - val_loss: 631480.3125 - val_mae: 641.2228
Epoch 131/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 395041.5625 - mae: 511.0983 - val_loss: 627904.5000 - val_mae: 638.5987
Epoch 132/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 391177.9688 - mae: 508.3416 - val_loss: 619610.3125 - val_mae: 634.0206
Epoch 133/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 388709.8750 - mae: 507.1099 - val_loss: 612086.9375 - val_mae: 629.9150
Epoch 134/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 385298.4688 - mae: 505.0811 - val_loss: 600829.8750 - val_mae: 623.8533
Epoch 135/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 382033.3438 - mae: 503.4261 - val_loss: 594543.7500 - val_mae: 620.1293
Epoch 136/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 378983.1562 - mae: 501.3820 - val_loss: 586650.6875 - val_mae: 615.6729
Epoch 137/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 375824.4062 - mae: 499.2051 - val_loss: 580900.4375 - val_mae: 612.2075
Epoch 138/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 372604.5625 - mae: 496.8527 - val_loss: 574060.0000 - val_mae: 608.2508
Epoch 139/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 369185.5938 - mae: 494.8760 - val_loss: 565118.1875 - val_mae: 603.0422
Epoch 140/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 366053.1562 - mae: 493.1281 - val_loss: 555689.3125 - val_mae: 597.3749
Epoch 141/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 362875.5938 - mae: 490.8026 - val_loss: 551680.0625 - val_mae: 594.5787
Epoch 142/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 359733.1562 - mae: 488.5848 - val_loss: 544673.8750 - val_mae: 590.2332
Epoch 143/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 356815.4062 - mae: 486.8723 - val_loss: 537795.1875 - val_mae: 585.7553
Epoch 144/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 353620.6250 - mae: 484.8169 - val_loss: 528297.6875 - val_mae: 580.2285
Epoch 145/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 351015.0625 - mae: 483.2397 - val_loss: 522630.6250 - val_mae: 576.2562
Epoch 146/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 347879.5938 - mae: 481.2392 - val_loss: 512166.7500 - val_mae: 569.7382
Epoch 147/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 344896.5625 - mae: 479.1831 - val_loss: 505045.5000 - val_mae: 565.1479
Epoch 148/150
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 341746.0625 - mae: 476.9535 - val_loss: 498949.5938 - val_mae: 561.0153
Epoch 149/150

In [49]:
predictions = model.predict(test_X)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

In [53]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

# 1. Get predictions and flatten them
predictions = model.predict(test_X).flatten()
actual_answers = test_y.values

# 2. Calculate the metrics
mse = mean_squared_error(actual_answers, predictions)
rmse = np.sqrt(mse)
r2 = r2_score(actual_answers, predictions)

# 3. Print the results clearly
print("--- MODEL PERFORMANCE METRICS ---")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} grams")
print(f"R-squared Score (R2): {r2:.2f}")

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
--- MODEL PERFORMANCE METRICS ---
Mean Squared Error (MSE): 320367.44
Root Mean Squared Error (RMSE): 566.01 grams
R-squared Score (R2): 0.43