In [22]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras.models as km
from keras.models import Sequential
from keras import activations, initializers, regularizers, constraints
from keras.layers import Dense, Activation

In [2]:
df = sns.load_dataset("titanic")   
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
df.shape

(891, 15)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [7]:
df.duplicated().sum()

np.int64(107)

In [8]:
df.drop_duplicates()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [9]:
df.reset_index()

,index,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [10]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [11]:
df["age"].value_counts()

age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [12]:
df["age"].fillna(24,inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_14672\3424648428.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(24,inplace=True)

In [17]:
df["embark_town"].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [24]:
df["embark_town"].fillna("Southampton",inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_14672\3758564723.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["embark_town"].fillna("Southampton",inplace=True)

In [25]:
df["embarked"].value_counts()

embarked
S     644
C     168
Q      77
24      2
Name: count, dtype: int64

In [26]:
df["embarked"].fillna("Southampton",inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_14672\1650730070.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["embarked"].fillna("Southampton",inplace=True)

In [ ]:
df.drop(columns=['deck'], inplace=True)

In [27]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [29]:
# Encode each column separately using pandas factorize
df['sex'] = pd.factorize(df['sex'])[0]
df['embarked'] = pd.factorize(df['embarked'])[0]
df['class'] = pd.factorize(df['class'])[0]
df['who'] = pd.factorize(df['who'])[0]
df['embark_town'] = pd.factorize(df['embark_town'])[0]
df['alive'] = pd.factorize(df['alive'])[0]
df['adult_male'] = pd.factorize(df['adult_male'])[0]
df['alone'] = pd.factorize(df['alone'])[0]

In [31]:
df["alive"].value_counts()

alive
0    549
1    342
Name: count, dtype: int64

In [32]:

X = df.drop(columns=['survived', 'alive'])
y = df['survived']

In [33]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state =123)

In [34]:
 sc = StandardScaler()
 train_X = sc.fit_transform(train_X)
 test_X = sc.transform(test_X)

In [40]:
model = Sequential()
model.add(Dense(units = 11, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [41]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 11)             │           143 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 6)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 4)              │            28 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 248 (992.00 B)

 Trainable params: 248 (992.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
# Change the loss function and add the metrics parameter
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [43]:
print(train_X.shape)
print(train_y.shape)

(623, 12)
(623,)

In [44]:
model.fit(train_X, train_y, epochs=30, batch_size=32, validation_split=0.1)

# Evaluate the model
mse = model.evaluate(test_X, test_y)
print(f'acuuracy: {mse}')

Epoch 1/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.6214 - loss: 0.6923 - val_accuracy: 0.4921 - val_loss: 0.6933
Epoch 2/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6214 - loss: 0.6903 - val_accuracy: 0.4921 - val_loss: 0.6934
Epoch 3/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6214 - loss: 0.6878 - val_accuracy: 0.4921 - val_loss: 0.6930
Epoch 4/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6214 - loss: 0.6823 - val_accuracy: 0.4921 - val_loss: 0.6910
Epoch 5/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6214 - loss: 0.6713 - val_accuracy: 0.4921 - val_loss: 0.6855
Epoch 6/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6214 - loss: 0.6491 - val_accuracy: 0.4921 - val_loss: 0.6746
Epoch 7/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6214 - loss: 0.6124 - val_accuracy: 0.4921 - val_loss: 0.6610
Epoch 8/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6214 - loss: 0.5710 - val_accuracy: 0.4921 - val_loss: 0.6534
Epoch 9/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6214 - loss: 0.5422 - val_accuracy: 0.4921 - val_loss: 0.6555
Epoch 10/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7696 - loss: 0.5307 - val_accuracy: 0.7302 - val_loss: 0.6536
Epoch 11/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8321 - loss: 0.5230 - val_accuracy: 0.7619 - val_loss: 0.6420
Epoch 12/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.5144 - val_accuracy: 0.7619 - val_loss: 0.6330
Epoch 13/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8357 - loss: 0.5052 - val_accuracy: 0.7778 - val_loss: 0.6173
Epoch 14/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8286 - loss: 0.4942 - val_accuracy: 0.7937 - val_loss: 0.6011
Epoch 15/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8250 - loss: 0.4830 - val_accuracy: 0.7937 - val_loss: 0.5847
Epoch 16/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8286 - loss: 0.4701 - val_accuracy: 0.7937 - val_loss: 0.5698
Epoch 17/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8268 - loss: 0.4581 - val_accuracy: 0.7937 - val_loss: 0.5544
Epoch 18/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8304 - loss: 0.4470 - val_accuracy: 0.7937 - val_loss: 0.5409
Epoch 19/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8321 - loss: 0.4359 - val_accuracy: 0.7937 - val_loss: 0.5254
Epoch 20/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8357 - loss: 0.4283 - val_accuracy: 0.7937 - val_loss: 0.5207
Epoch 21/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8375 - loss: 0.4219 - val_accuracy: 0.7778 - val_loss: 0.5158
Epoch 22/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8357 - loss: 0.4169 - val_accuracy: 0.7778 - val_loss: 0.5092
Epoch 23/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8357 - loss: 0.4129 - val_accuracy: 0.7619 - val_loss: 0.5088
Epoch 24/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8357 - loss: 0.4101 - val_accuracy: 0.7778 - val_loss: 0.5025
Epoch 25/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.4073 - val_accuracy: 0.7619 - val_loss: 0.5066
Epoch 26/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8429 - loss: 0.4055 - val_accuracy: 0.7619 - val_loss: 0.5019
Epoch 27/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8375 - loss: 0.4038 - val_accuracy: 0.7619 - val_loss: 0.5005
Epoch 28/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8411 - loss: 0.4022 - val_accuracy: 0.7619 - val_loss: 0.5039
Epoch 29/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8411 - loss: 0.4003 - val_accuracy: 0.7619 - val_loss: 0.5020
Epoch 30/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8411 - loss: 0.3992 - val_accuracy: 0.7619 - val_loss: 0.5026
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8396 - loss: 0.3992
acuuracy: [0.39916756749153137, 0.8395522236824036]

In [45]:
predictions = model.predict(test_X)
predictions

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

array([[0.8474194 ],
       [0.14927599],
       [0.33986583],
       [0.17814514],
       [0.1322844 ],
       [0.10647166],
       [0.88157487],
       [0.9129538 ],
       [0.7424164 ],
       [0.4222692 ],
       [0.6229586 ],
       [0.42712918],
       [0.9045752 ],
       [0.10016858],
       [0.9178704 ],
       [0.76014876],
       [0.9294007 ],
       [0.31450284],
       [0.25678504],
       [0.11627314],
       [0.3860245 ],
       [0.9666383 ],
       [0.10970876],
       [0.26896805],
       [0.2351534 ],
       [0.0914779 ],
       [0.1036869 ],
       [0.9493203 ],
       [0.10816447],
       [0.17489886],
       [0.45068985],
       [0.8647731 ],
       [0.11816756],
       [0.1283561 ],
       [0.16342576],
       [0.70912373],
       [0.07772333],
       [0.06818438],
       [0.9200623 ],
       [0.3081273 ],
       [0.96548754],
       [0.13103767],
       [0.6289674 ],
       [0.24395877],
       [0.11364175],
       [0.13538985],
       [0.9220289 ],
       [0.22427005],
       [0.1061497 ],
       [0.9186961 ],
       [0.66292167],
       [0.2766101 ],
       [0.10552243],
       [0.08620708],
       [0.13745391],
       [0.14927296],
       [0.09895304],
       [0.10963321],
       [0.2913621 ],
       [0.16621606],
       [0.928193  ],
       [0.95939404],
       [0.94232565],
       [0.9457173 ],
       [0.10031447],
       [0.08780956],
       [0.09592819],
       [0.0931756 ],
       [0.28484535],
       [0.936567  ],
       [0.92636347],
       [0.06931375],
       [0.28333175],
       [0.27316102],
       [0.10508973],
       [0.09522143],
       [0.06449649],
       [0.10478091],
       [0.9428309 ],
       [0.9495234 ],
       [0.4893417 ],
       [0.09903599],
       [0.20519271],
       [0.14927599],
       [0.10079359],
       [0.11943348],
       [0.88353854],
       [0.13491286],
       [0.29171634],
       [0.09890091],
       [0.5488262 ],
       [0.19764788],
       [0.08839172],
       [0.2137423 ],
       [0.33003086],
       [0.10801607],
       [0.94273245],
       [0.93748105],
       [0.08902941],
       [0.8090004 ],
       [0.23716138],
       [0.29392844],
       [0.21347032],
       [0.84375566],
       [0.17489886],
       [0.26400417],
       [0.09796764],
       [0.14230819],
       [0.08620708],
       [0.89114934],
       [0.9474118 ],
       [0.27107078],
       [0.9494198 ],
       [0.09016605],
       [0.09790535],
       [0.09544056],
       [0.17408578],
       [0.08236461],
       [0.10960522],
       [0.31338942],
       [0.10816447],
       [0.07677838],
       [0.22291161],
       [0.17547834],
       [0.14137214],
       [0.12451859],
       [0.22547771],
       [0.3024387 ],
       [0.704039  ],
       [0.10662856],
       [0.9377815 ],
       [0.09395432],
       [0.09923632],
       [0.6427071 ],
       [0.9114951 ],
       [0.10962048],
       [0.95426637],
       [0.40670228],
       [0.10088117],
       [0.91801816],
       [0.1132596 ],
       [0.336457  ],
       [0.1610618 ],
       [0.9367004 ],
       [0.74010694],
       [0.09609058],
       [0.11613906],
       [0.11814206],
       [0.09700793],
       [0.94118327],
       [0.29154596],
       [0.16911049],
       [0.4855947 ],
       [0.11273537],
       [0.93734586],
       [0.14927599],
       [0.896021  ],
       [0.8467713 ],
       [0.8655942 ],
       [0.91008383],
       [0.876176  ],
       [0.20209654],
       [0.35245705],
       [0.9353182 ],
       [0.24025908],
       [0.9452596 ],
       [0.67336977],
       [0.10662856],
       [0.704054  ],
       [0.1562609 ],
       [0.10223117],
       [0.2909481 ],
       [0.24307548],
       [0.16079935],
       [0.17488189],
       [0.07457349],
       [0.95166236],
       [0.14927296],
       [0.13134012],
       [0.95273834],
       [0.16276656],
       [0.11262271],
       [0.18029854],
       [0.46049488],
       [0.0904941 ],
       [0.9642995 ],
       [0.15548594],
       [0.93544483],
       [0.10547812],
       [0.7317351 ],
       [0.1476378 ],
       [0.10042759],
       [0.90386987],
       [0.11427753],
       [0.6803711 ],
       [0.4464476 ],
       [0.08639174],
       [0.3557715 ],
       [0.9356422 ],
       [0.10072506],
       [0.94681203],
       [0.704054  ],
       [0.22494794],
       [0.169511  ],
       [0.197227  ],
       [0.10816447],
       [0.17489886],
       [0.9374245 ],
       [0.66783345],
       [0.07817914],
       [0.0947213 ],
       [0.9252081 ],
       [0.5075091 ],
       [0.08571498],
       [0.09196093],
       [0.14927599],
       [0.11816756],
       [0.177216  ],
       [0.15310247],
       [0.14771076],
       [0.10079359],
       [0.2695868 ],
       [0.13944674],
       [0.22481053],
       [0.83982635],
       [0.17311631],
       [0.13134012],
       [0.1473973 ],
       [0.12545869],
       [0.9119657 ],
       [0.42538446],
       [0.04846271],
       [0.46141678],
       [0.08668309],
       [0.12813377],
       [0.09608603],
       [0.9311778 ],
       [0.22529104],
       [0.9441749 ],
       [0.11923449],
       [0.09254   ],
       [0.29173866],
       [0.55322605],
       [0.10079359],
       [0.14927599],
       [0.08193298],
       [0.09157525],
       [0.63855517],
       [0.24613585],
       [0.24158134],
       [0.08757336],
       [0.30626246],
       [0.20618702],
       [0.11471827],
       [0.11834624],
       [0.9636977 ],
       [0.45204297],
       [0.43511465],
       [0.70409894],
       [0.3870493 ],
       [0.09224263],
       [0.394784  ],
       [0.09648282],
       [0.10825767],
       [0.28560755],
       [0.936751  ],
       [0.15034565],
       [0.9243021 ]], dtype=float32)

In [46]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix


probabilities = model.predict(test_X)


final_predictions = (probabilities > 0.5).astype(int)


accuracy = accuracy_score(test_y, final_predictions)
print(f"Classification Accuracy: {accuracy * 100:.2f}%")

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Classification Accuracy: 83.96%