In [19]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

In [46]:

df = sns.load_dataset("mpg")

In [47]:
df.shape

(398, 9)

In [48]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [49]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [51]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [78]:
df["horsepower"].value_counts()

horsepower
150.0    22
90.0     20
88.0     19
110.0    18
100.0    17
         ..
61.0      1
93.0      1
148.0     1
152.0     1
82.0      1
Name: count, Length: 93, dtype: int64

In [81]:
df.fillna({"horsepower":150},inplace=True)

In [82]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["name"] = le.fit_transform(df["name"])
df["origin"] = le.fit_transform(df["origin"])

In [83]:

X = df.drop(columns=['mpg'])
y = df['mpg']

In [84]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,8,307.0,130.0,3504,12.0,70,2,49
1,8,350.0,165.0,3693,11.5,70,2,36
2,8,318.0,150.0,3436,11.0,70,2,231
3,8,304.0,150.0,3433,12.0,70,2,14
4,8,302.0,140.0,3449,10.5,70,2,161
...,...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,2,153
394,4,97.0,52.0,2130,24.6,82,0,301
395,4,135.0,84.0,2295,11.6,82,2,119
396,4,120.0,79.0,2625,18.6,82,2,159
397,4,119.0,82.0,2720,19.4,82,2,69

In [85]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [86]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [87]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [88]:
sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [89]:
svr = SVR(kernel='rbf')

In [90]:
svr.fit(X_train_scaled,y_train)

SVR()

In [91]:
y_pred_scaled = svr.predict(X_test_scaled)

In [92]:
result = pd.DataFrame({
    'Actual Maxhr': y_test,
    'Predicted Maxhr': y_pred_scaled.flatten()
})

result

     Actual Maxhr  Predicted Maxhr
198          33.0        32.240503
396          28.0        29.314480
33           19.0        20.537838
208          13.0        16.239421
93           14.0        14.422180
..            ...              ...
249          19.9        19.463220
225          17.5        17.960134
367          28.0        27.768768
175          29.0        27.974296
285          17.0        18.104896

[80 rows x 2 columns]

In [93]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np


r2 = r2_score(y_test, y_pred_scaled)
print(f"R2 Score (Regression Accuracy): {r2:.4f}")


mae = mean_absolute_error(y_test, y_pred_scaled)
print(f"Mean Absolute Error: {mae:.2f} BPM")


rmse = np.sqrt(mean_squared_error(y_test, y_pred_scaled))
print(f"Root Mean Squared Error: {rmse:.2f} BPM")

R2 Score (Regression Accuracy): 0.8609
Mean Absolute Error: 1.87 BPM
Root Mean Squared Error: 2.74 BPM